name: Renovate

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  schedule:
    - cron: '0 */12 * * *'  #runs every 12 hours
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@v1
        with:
          private_key: ${{ secrets.PRIVATE_KEY }}
          #app-id: ${{ vars.APP_ID }}
          app_id: ${{ secrets.APP_ID }}
          #installation_retrieval_mode: organization
          
      #- name: Retrieve secrets
      #  uses: gkiranch/github-actions/local-repos/aws-secretsmanager-get-secrets@master
      #  env:
      #    AWS_REGION: us-east-1
      #  with:
      #    secret-ids: |
      #
      #    parse-json-secrets: true
      - name: Validate and set repositories
        run: |
          JSON=$(yq e -o=json . < repos/repositories.yaml)
          echo $JSON | jq . > /dev/null
          if [ $? -eq 0 ]; then
            JSON=$(echo $JSON | tr -d '\n')
            echo "REPOSITORIES=$JSON" >> $GITHUB_ENV
          else
            echo "Invalid JSON"
            exit 1
          fi
      - name: Run Renovate
        uses: renovatebot/github-action@v39.1.1
        with:
          configurationFile: config.js
          token: '${{ steps.get_token.outputs.token }}'
          #token: '${{ secrets.RENOVATE_TOKEN }}'
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|GITHUB_COM_TOKEN|NODE_OPTIONS|REPOSITORIES|OTEL_EXPORTER_OTLP_ENDPOINT)$"
        env:
          LOG_LEVEL: debug
          # LOG_FORMAT: json
          REPOSITORIES: ${{ env.REPOSITORIES }}
          RENOVATE_DRY_RUN: ${{ github.event_name == 'pull_request' && 'full' || '' }}
          RENOVATE_ART_SECRET_USERNAME: ${{ secrets.RENOVATE_ART_SECRET_USERNAME }}
          RENOVATE_ART_SECRET_PASSWORD: ${{ secrets.RENOVATE_ART_SECRET_PASSWORD }}
          OTEL_EXPORTER_OTLP_ENDPOINT: "http://ec2-18-117-118-1.us-east-2.compute.amazonaws.com:4318"
          RENOVATE_TRACING_CONSOLE_EXPORTER: "true"
      
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'failure,success,warning'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}